- aquawatch_mobile_app/README.md
- aquawatch_mobile_app/src/screens/AiScreen.js
- aquawatch_mobile_app/src/screens/AiScreenNoServer.js
Removed API Key from being hosted in a public repository. 
Old key in commit no longer works.
> Remove api key

- aquawatch_mobile_app/src/screens/Data screens/DataChoate.js
Updating link embeded in choate pond to display the updated python data viz
> update for choate pond

- aquawatch_mobile_app/app.json
- aquawatch_mobile_app/eas.json
- aquawatch_mobile_app/package-lock.json
- aquawatch_mobile_app/package.json
- **broken packages**
- **finally android complice fixed**
> EAS Deploy

- .github/pull_request_template.md
- .github/workflows/backend_delploy.yml
A push to main should now automatically upload backend changes
> trigger deployment by workflow

- .github/workflows/backend_delploy.yml
- Fix workflow issues preventing deploy
- Path was specfied incorrectly
> Fix workflow issues preventing deploy

- .github/workflows/frontend_build.yml
- Added workflow to build frontend to Expo
> Workflow for Frontend Builds

- aquawatch_mobile_app/App.js
> no longer settings

- backend_py/app.py
> demo change trigger build

- .github/workflows/dev_backend_deploy.yml
- Fixed bug that allowed anyone to deploy...
> Fix anyone can deploy 

- aquawatch_mobile_app/src/screens/CurrentData.jsx
- testing/dataCleaner.js
- More explnation to starter code
> clarify w/comments

- .github/workflows/check_build.yml
- Testing GH Actions to verify builds before merging
> [Build] Check PRs for errors

- .github/workflows/check_build.yml
> Error handle & Packages Patches

- aquawatch_mobile_app/src/contexts/ColorSchemeProvider.jsx
- aquawatch_mobile_app/src/contexts/CurrentDataContext.jsx
- aquawatch_mobile_app/src/contexts/GraphDataContext.jsx
- To be investigated, but reverting changes that would cause infinite dependencies
> [Revert] Revert changes causing infinite queries

- README.md
- aquawatch_mobile_app/README.md
- Improved starting instructions
> [Docs] Fixes, clarifications

- aquawatch_mobile_app/package-lock.json
- aquawatch_mobile_app/package.json
- aquawatch_mobile_app/src/hooks/jsons/units.json
- aquawatch_mobile_app/src/screens/CurrentData.jsx
- package-lock.json
- Fix bug that was causing app to crash due to missing checks
- Fixed conductivity unit
> [Bug] Fix bugs including those causing the app to crash

- aquawatch_mobile_app/package-lock.json
- aquawatch_mobile_app/package.json
- aquawatch_mobile_app/src/screens/Graph.jsx
- aquawatch_mobile_app/src/screens/HomeScreen.jsx
- Now use `react-native-reanimated-carousel`
> New carousel library for carousel

- aquawatch_mobile_app/package-lock.json
- aquawatch_mobile_app/package.json
- Bug within Expo/lan-network was causing development issues, this PR fixes them thanks to their update!
> [Dependencies] Fixes https://github.com/expo/expo/issues/36710 :)

- aquawatch_mobile_app/src/screens/CurrentData.jsx
- Adjusted the water temperature text to align with the other 5 measures
> Adjusted water temp. alignment

- aquawatch_mobile_app/metro.config.js
-   Remove unneccary config that is fixed via package patch.
> Remove legacy metro config settings

- aquawatch_mobile_app/app.config.json
- aquawatch_mobile_app/app/(tabs)/settings/versionHistory.tsx
- aquawatch_mobile_app/components/visualizations/monthlyData/MonthlyDataCardFront.tsx
> AWM-3 - Fix darkmode bug for graph heighlight

- .github/workflows/check_build.yml
- .vscode/settings.json
- aquawatch_mobile_app/.cspell.json
- aquawatch_mobile_app/package-lock.json
- aquawatch_mobile_app/package.json
> AWM-35 - Add simple command for testing

- .github/ISSUE_TEMPLATE/custom.yaml
- Convereted to correct format
> Update and rename custom.md to custom.yaml

- aquawatch_mobile_app/package-lock.json
- Please see this: https://github.com/form-data/form-data/security/advisories/GHSA-fjxv-7rqg-78g4
- Fixed with `npm audit fix`
- npm run test passed with no errors
> Patch `form-data` vulnerability

- aquawatch_mobile_app/package-lock.json
- aquawatch_mobile_app/package.json
- aquawatch_mobile_app/patches/victory-native+41.17.4.patch
- Removed an buggy override - https://github.com/Shopify/react-native-skia has bugs in that version causing errors
> AWM-12b - Fix axis not showing in first render

- aquawatch_mobile_app/package-lock.json
- aquawatch_mobile_app/package.json
- Fixes: https://github.com/bluecolab/BlueColab_MobileDataViz/issues/176
> AWM-45 - Fix crashing when opening Air Quality Screen

- aquawatch_mobile_app/app.config.json
- aquawatch_mobile_app/app/(tabs)/settings/versionHistory.tsx
- aquawatch_mobile_app/package-lock.json
- aquawatch_mobile_app/package.json
> AWM-1.8.5 - Version Release

- aquawatch_mobile_app/app/(tabs)/settings/versionHistory.tsx
> AWM-1.8.7 - Version Release

- aquawatch_mobile_app/.cspell.json
- aquawatch_mobile_app/app/(tabs)/currentData.tsx
- aquawatch_mobile_app/app/(tabs)/home/historicData.tsx
- aquawatch_mobile_app/app/(tabs)/home/index.tsx
- aquawatch_mobile_app/app/(tabs)/settings/index.tsx
- aquawatch_mobile_app/components/SettingsDropdown.tsx
- aquawatch_mobile_app/components/visualizations/QuickCurrentData.tsx
- aquawatch_mobile_app/components/visualizations/monthlyData/MonthlyDataCard.tsx
- aquawatch_mobile_app/contexts/GraphDataContext.tsx
- aquawatch_mobile_app/hooks/useGetWaterData.ts
- aquawatch_mobile_app/package.json
- aquawatch_mobile_app/utils/extractLastData.ts
Unit conversions in progress. Something is causing the new units not to show properly.
> AWM-29 Unit Conversions

- aquawatch_mobile_app/components/visualizations/monthlyData/Graph.tsx
- aquawatch_mobile_app/components/visualizations/monthlyData/MonthlyDataCardFront.tsx
Independent file Graph was created and configured
> AWM-13 - Move graph to it's own component
